[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-meros.json"

[target.x86_64-meros]
rustflags = []


[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=gold"]
linker = "gcc"
